"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { accessoryProducts } from "@/lib/accessories";

type Language = "en" | "ja" | "my";
type ShopItem = { id:string; name:string; price:number; image:string; position:string; stock:number; description:string; kind?:"motorcycle"|"accessory" };
type Bike = ShopItem & { category:string; engine:string; year:number; color:string; condition:"New"|"Used" };
type Accessory = ShopItem & { category:string };
type CartItem = ShopItem & { quantity:number };
type TrackedOrder = { orderNumber:string; status:string; items:Array<{name:string;quantity:number;price:number}>; total:number; createdAt:string; paidAt?:string|null };

const bikes: Bike[] = [
  { id:"gw-125-city", kind:"motorcycle", name:"GW 125 CITY", category:"Street", engine:"125 cc", price:298000, image:"/images/color-bike-sheet-1.png", position:"0% 0%", year:2026, color:"Sunset Orange", condition:"New", stock:4, description:"Easy handling, low running costs and a comfortable everyday ride." },
  { id:"gw-155-r", name:"GW 155 R", category:"Sport", engine:"155 cc", price:428000, image:"/images/color-bike-sheet-1.png", position:"100% 100%", year:2026, color:"Racing Blue", condition:"New", stock:3, description:"A lightweight sport model for daily commutes and weekend roads." },
  { id:"gw-250-roadster", name:"GW 250 ROADSTER", category:"Street", engine:"249 cc", price:568000, image:"/images/color-bike-sheet-3.png", position:"0% 100%", year:2025, color:"Pearl White", condition:"New", stock:2, description:"Balanced power and upright comfort for town and highway riding." },
  { id:"gw-300-x", name:"GW 300 X", category:"Adventure", engine:"292 cc", price:698000, image:"/images/color-bike-sheet-1.png", position:"100% 0%", year:2026, color:"Forest Green", condition:"New", stock:3, description:"Long-travel suspension and practical luggage-ready touring ability." },
  { id:"gw-400-classic", name:"GW 400 CLASSIC", category:"Classic", engine:"398 cc", price:748000, image:"/images/color-bike-sheet-1.png", position:"0% 100%", year:2025, color:"Burgundy", condition:"Used", stock:1, description:"Traditional road-bike styling with simple, modern reliability." },
  { id:"gw-500-naked", name:"GW 500 NAKED", category:"Street", engine:"471 cc", price:868000, image:"/images/color-bike-sheet-2.png", position:"0% 0%", year:2026, color:"Metallic Red", condition:"New", stock:2, description:"Strong mid-range power with a relaxed riding position." },
  { id:"gw-650-heritage", name:"GW 650 HERITAGE", category:"Classic", engine:"648 cc", price:980000, image:"/images/color-bike-sheet-2.png", position:"100% 0%", year:2025, color:"British Green", condition:"Used", stock:1, description:"A twin-cylinder classic made for unhurried Sunday rides." },
  { id:"gw-700-street", name:"GW 700 STREET", category:"Street", engine:"689 cc", price:1120000, image:"/images/color-bike-sheet-2.png", position:"0% 100%", year:2026, color:"Electric Blue", condition:"New", stock:2, description:"Responsive torque, confident brakes and everyday usability." },
  { id:"gw-750-tourer", name:"GW 750 TOURER", category:"Adventure", engine:"745 cc", price:1380000, image:"/images/color-bike-sheet-3.png", position:"0% 0%", year:2026, color:"Desert Sand", condition:"New", stock:2, description:"Comfortable wind protection and range for long-distance travel." },
  { id:"gw-900-adventure", name:"GW 900 ADVENTURE", category:"Adventure", engine:"895 cc", price:1580000, image:"/images/color-bike-sheet-3.png", position:"100% 0%", year:2026, color:"Titanium", condition:"New", stock:3, description:"Built for two-up touring, mountain roads and long days out." },
  { id:"gw-900-cruiser", name:"GW 900 CRUISER", category:"Cruiser", engine:"903 cc", price:1690000, image:"/images/color-bike-sheet-2.png", position:"100% 100%", year:2025, color:"Deep Purple", condition:"Used", stock:1, description:"Low-seat comfort and steady V-twin character for open roads." },
  { id:"gw-1200-muscle", name:"GW 1200 MUSCLE", category:"Cruiser", engine:"1,202 cc", price:2180000, image:"/images/cruiser-expansion-sheet.png", position:"0% 0%", year:2026, color:"Inferno Red", condition:"New", stock:2, description:"A low, muscular V-twin cruiser with strong torque and a planted ride." },
  { id:"gw-1200-bobber", name:"GW 1200 BOBBER", category:"Bobber", engine:"1,202 cc", price:2280000, image:"/images/cruiser-expansion-sheet.png", position:"100% 0%", year:2026, color:"Copper Bronze", condition:"New", stock:1, description:"Stripped-back styling, solo-seat character and an easy low stance." },
  { id:"gw-1300-chopper", name:"GW 1300 CHOPPER", category:"Chopper", engine:"1,304 cc", price:2480000, image:"/images/cruiser-expansion-sheet.png", position:"0% 100%", year:2026, color:"Royal Blue", condition:"New", stock:1, description:"Long-fork custom proportions with relaxed controls for open-road rides." },
  { id:"gw-1800-grand-tour", name:"GW 1800 GRAND TOUR", category:"Touring", engine:"1,868 cc", price:3280000, image:"/images/cruiser-expansion-sheet.png", position:"100% 100%", year:2026, color:"Champagne Gold", condition:"New", stock:1, description:"Full-size touring comfort with windshield, luggage and passenger support." },
  { id:"gw-1000-rr", name:"GW 1000 RR", category:"Sport", engine:"999 cc", price:1980000, image:"/images/color-bike-sheet-3.png", position:"100% 100%", year:2026, color:"Lime Green", condition:"New", stock:2, description:"High-performance engineering for experienced sport riders." },
];

const recommendedIds = new Set(["gw-125-city","gw-300-x","gw-1200-muscle","gw-1800-grand-tour"]);
const accessories: Accessory[] = accessoryProducts.map((item)=>({...item,kind:"accessory",category:item.group}));
const accessoryGroups = ["All","Helmets","Jackets","Gloves","Boots","Luggage","Phone mounts","Security","Covers"] as const;
function accessoryGroup(id:string){return accessories.find((item)=>item.id===id)?.category??"Helmets"}
const copy = {
  en:{ bikes:"Motorcycles",recommended:"Recommended",service:"Service",contact:"Contact",cart:"Cart",collection:"NEW COLLECTION",eyebrow:"MOTORCYCLES · OKINAWA",title:"Ride beyond",accent:"the ordinary.",lead:"Street, sport, adventure and heavyweight cruisers—find the machine that matches the way you ride.",view:"View motorcycles",test:"Book a test ride",available:"Models available",warranty:"Warranty included",support:"Service support",stock:"CURRENT STOCK",choose:"Choose your motorcycle",intro:"Compare riding style, engine size and price. Start with our recommended models if you are unsure.",all:"All",search:"Search by model or color",showing:"Showing",units:"motorcycles",filters:"Filters",condition:"Condition",price:"Price range",any:"Any",new:"New",used:"Used",under1:"Under ¥1M",oneToTwo:"¥1M–¥2M",over2:"Over ¥2M",details:"View details",add:"Add to cart",favorite:"Favorite",year:"Year",color:"Color",status:"Availability",inStock:"In stock",serviceLabel:"THE GOLDEN STANDARD",serviceTitle:"Support for every road, before and after purchase.",select:"Expert selection",selectText:"Every model is inspected by people who understand motorcycles and Okinawa roads.",finance:"Flexible finance",financeText:"Clear payment plans make it easier to choose a motorcycle with confidence.",care:"After-sales care",careText:"Inspections, maintenance and rider support continue after delivery.",selection:"YOUR SELECTED ITEMS",empty:"Your cart is ready for a new road.",explore:"Explore models",total:"Total",continue:"Continue to request",request:"PURCHASE REQUEST",requestTitle:"Tell us how to contact you",name:"Full name",email:"Email",phone:"Phone",address:"Address",send:"Send request",sending:"Sending…",demo:"Portfolio demonstration only. No payment is charged.",received:"REQUEST RECEIVED",success:"Your next road starts here.",saved:"We saved your request. A Golden Wheel specialist will contact you.",return:"Return to showroom",contactLabel:"VISIT · ASK · RIDE",contactTitle:"Let’s find your next motorcycle.",contactText:"Ask about stock, finance, maintenance or reserve a test ride. This is a demonstration showroom.",hours:"Opening hours",hoursText:"Mon–Sat · 10:00–19:00",location:"Location",locationText:"Naha, Okinawa (Demo)",call:"Phone",callText:"098-000-0000 (Demo)",message:"Send an inquiry",menu:"Open menu",close:"Close",noResults:"No motorcycles match those filters.",clear:"Clear filters" },
  ja:{ bikes:"バイク一覧",recommended:"おすすめ",service:"サービス",contact:"お問い合わせ",cart:"カート",collection:"新しいコレクション",eyebrow:"モーターサイクル · 沖縄",title:"いつもの道を",accent:"特別な道へ。",lead:"街乗り、スポーツ、アドベンチャー、大型クルーザーから、あなたに合う一台を見つけてください。",view:"バイクを見る",test:"試乗を予約",available:"取扱モデル",warranty:"保証付き",support:"整備サポート",stock:"現在のラインナップ",choose:"あなたの一台を選ぶ",intro:"タイプ・排気量・価格から比較できます。迷った場合は、おすすめモデルからご覧ください。",all:"すべて",search:"モデル名・カラーで検索",showing:"表示中",units:"台",filters:"絞り込み",condition:"車両状態",price:"価格帯",any:"すべて",new:"新車",used:"中古車",under1:"100万円未満",oneToTwo:"100万〜200万円",over2:"200万円以上",details:"詳細を見る",add:"カートに追加",favorite:"お気に入り",year:"年式",color:"カラー",status:"在庫",inStock:"在庫あり",serviceLabel:"ゴールデン・スタンダード",serviceTitle:"購入前も納車後も、安心できるサポート。",select:"プロによる選定",selectText:"バイクと沖縄の道路を知るスタッフが、すべてのモデルを確認しています。",finance:"選べる支払いプラン",financeText:"分かりやすいプランで、安心してバイクを選べます。",care:"アフターサポート",careText:"納車後も点検・整備・ライダーサポートを続けます。",selection:"選択したバイク",empty:"カートは空です。",explore:"バイクを見る",total:"合計",continue:"購入相談へ",request:"購入相談",requestTitle:"連絡先を入力してください",name:"お名前",email:"メール",phone:"電話番号",address:"住所",send:"相談を送信",sending:"送信中…",demo:"ポートフォリオ用のデモです。支払いは発生しません。",received:"相談を受け付けました",success:"次の道は、ここから。",saved:"ご相談を保存しました。担当者からご連絡します。",return:"ショールームに戻る",contactLabel:"来店 · 相談 · 試乗",contactTitle:"次の一台を一緒に探しましょう。",contactText:"在庫、支払い、整備、試乗についてご相談ください。この店舗情報はデモです。",hours:"営業時間",hoursText:"月〜土 · 10:00〜19:00",location:"所在地",locationText:"沖縄県那覇市（デモ）",call:"電話",callText:"098-000-0000（デモ）",message:"お問い合わせ",menu:"メニューを開く",close:"閉じる",noResults:"条件に合うバイクがありません。",clear:"条件をクリア" },
  my:{ bikes:"ဆိုင်ကယ်များ",recommended:"အကြံပြု",service:"ဝန်ဆောင်မှု",contact:"ဆက်သွယ်ရန်",cart:"ခြင်းတောင်း",collection:"မော်ဒယ်အသစ်များ",eyebrow:"ဆိုင်ကယ် · အိုကီနာဝါ",title:"သာမန်လမ်းထက်",accent:"ပိုဝေးစီးပါ။",lead:"မြို့တွင်း၊ Sport၊ Adventure နဲ့ အကြီးစား Cruiser များထဲမှ သင်နဲ့ကိုက်ညီတဲ့ ဆိုင်ကယ်ကို ရွေးပါ။",view:"ဆိုင်ကယ်များကြည့်မယ်",test:"စမ်းစီးရန်စာရင်းပေးမယ်",available:"ရရှိနိုင်သောမော်ဒယ်",warranty:"အာမခံပါဝင်သည်",support:"ပြုပြင်ထိန်းသိမ်းမှု",stock:"လက်ရှိဆိုင်ကယ်များ",choose:"သင့်ဆိုင်ကယ်ကို ရွေးပါ",intro:"အမျိုးအစား၊ အင်ဂျင်နဲ့ ဈေးနှုန်းအလိုက် နှိုင်းယှဉ်နိုင်ပါတယ်။ မသေချာရင် အကြံပြုမော်ဒယ်ကနေ စပါ။",all:"အားလုံး",search:"မော်ဒယ် သို့မဟုတ် အရောင်ရှာရန်",showing:"ပြသထားသည်",units:"စီး",filters:"ရွေးချယ်စစ်ထုတ်ရန်",condition:"အခြေအနေ",price:"ဈေးနှုန်း",any:"အားလုံး",new:"အသစ်",used:"အသုံးပြုပြီး",under1:"ယန်း ၁ သန်းအောက်",oneToTwo:"ယန်း ၁–၂ သန်း",over2:"ယန်း ၂ သန်းအထက်",details:"အသေးစိတ်ကြည့်မယ်",add:"ခြင်းတောင်းထဲထည့်မယ်",favorite:"ကြိုက်နှစ်သက်မှု",year:"ခုနှစ်",color:"အရောင်",status:"လက်ကျန်",inStock:"လက်ကျန်ရှိ",serviceLabel:"GOLDEN ဝန်ဆောင်မှု",serviceTitle:"မဝယ်မီမှ ဝယ်ပြီးနောက်အထိ ယုံကြည်ရသောဝန်ဆောင်မှု။",select:"ကျွမ်းကျင်စွာရွေးချယ်ခြင်း",selectText:"ဆိုင်ကယ်နဲ့ အိုကီနာဝါလမ်းတွေကို နားလည်တဲ့ဝန်ထမ်းတွေက မော်ဒယ်တိုင်းကို စစ်ထားပါတယ်။",finance:"ငွေပေးချေမှုအစီအစဉ်",financeText:"ရှင်းလင်းတဲ့အစီအစဉ်တွေနဲ့ စိတ်ချစွာ ဆိုင်ကယ်ရွေးနိုင်ပါတယ်။",care:"ဝယ်ပြီးနောက်စောင့်ရှောက်မှု",careText:"ပို့ဆောင်ပြီးနောက်မှာလည်း စစ်ဆေး၊ ပြုပြင်နဲ့ ကူညီမှုဆက်ရှိပါတယ်။",selection:"ရွေးထားသောဆိုင်ကယ်",empty:"ခြင်းတောင်းထဲမှာ ဆိုင်ကယ်မရှိသေးပါ။",explore:"ဆိုင်ကယ်များကြည့်မယ်",total:"စုစုပေါင်း",continue:"ဝယ်ယူရန်ဆွေးနွေးမယ်",request:"ဝယ်ယူရန်ဆွေးနွေးမှု",requestTitle:"ဆက်သွယ်ရန်အချက်အလက်ဖြည့်ပါ",name:"နာမည်",email:"အီးမေးလ်",phone:"ဖုန်းနံပါတ်",address:"လိပ်စာ",send:"တောင်းဆိုချက်ပို့မယ်",sending:"ပို့နေသည်…",demo:"Portfolio သရုပ်ပြအတွက်သာဖြစ်ပြီး ငွေကောက်ခံခြင်းမရှိပါ။",received:"တောင်းဆိုချက်ရရှိပါပြီ",success:"သင့်ခရီးသစ် ဒီမှာစတင်ပါပြီ။",saved:"တောင်းဆိုချက်ကို သိမ်းထားပါပြီ။ တာဝန်ခံမှ ဆက်သွယ်ပါမယ်။",return:"ဆိုင်သို့ပြန်မယ်",contactLabel:"လာရောက် · ဆွေးနွေး · စမ်းစီး",contactTitle:"သင့်နောက်ဆိုင်ကယ်ကို အတူရှာကြမယ်။",contactText:"လက်ကျန်၊ ငွေပေးချေမှု၊ ပြုပြင်မှုနဲ့ စမ်းစီးခြင်းကို မေးနိုင်ပါတယ်။ ဒီဆိုင်အချက်အလက်က demo ဖြစ်ပါတယ်။",hours:"ဖွင့်ချိန်",hoursText:"တနင်္လာ–စနေ · 10:00–19:00",location:"တည်နေရာ",locationText:"Naha, Okinawa (Demo)",call:"ဖုန်း",callText:"098-000-0000 (Demo)",message:"မေးမြန်းရန်",menu:"Menu ဖွင့်ရန်",close:"ပိတ်ရန်",noResults:"ရွေးထားတဲ့အချက်တွေနဲ့ ကိုက်ညီတဲ့ဆိုင်ကယ်မရှိပါ။",clear:"အားလုံးပြန်ထားမယ်" }
};

export default function Home(){
  const [language,setLanguage]=useState<Language>("ja"); const [category,setCategory]=useState("All"); const [condition,setCondition]=useState("Any"); const [priceBand,setPriceBand]=useState("Any"); const [query,setQuery]=useState(""); const [cart,setCart]=useState<CartItem[]>([]); const [favorites,setFavorites]=useState<string[]>([]); const [selectedBike,setSelectedBike]=useState<Bike|null>(null); const [cartOpen,setCartOpen]=useState(false); const [checkoutOpen,setCheckoutOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false); const [submitting,setSubmitting]=useState(false); const [formError,setFormError]=useState(""); const [completedOrder,setCompletedOrder]=useState("");
  const [favoritesReady,setFavoritesReady]=useState(false); const [trackedOrder,setTrackedOrder]=useState<TrackedOrder|null>(null); const [tracking,setTracking]=useState(false); const [trackError,setTrackError]=useState(""); const [accessoryCategory,setAccessoryCategory]=useState<(typeof accessoryGroups)[number]>("All");
  const t=copy[language];
  const ui=language==="ja"?{accessoriesTitle:"ライディングギア＆アクセサリー",accessoriesText:"ヘルメット、プロテクター、収納、安全用品などをバイクと一緒にカートへ追加できます。",lookupTitle:"購入内容を確認",lookupText:"サンプルサイトのため、メールは不要です。購入後に表示される注文番号だけで確認できます。",orderNumber:"注文番号",check:"注文を確認",checking:"確認中…",confirmTitle:"注文を確認",demoPayment:"ポートフォリオ · デモ決済",locked:"カード決済 · デモのみ",lockedText:"決済情報はロックされているため入力できません。",noCharge:"実際の請求はありません",noChargeText:"メールや実際の決済は不要です。確認するとサンプル注文番号が発行されます。",confirm:"デモ注文を確定",confirming:"確定中…",orderTip:"「注文状況」で注文番号だけを入力すると再確認できます。",contactNote:"ポートフォリオのサンプルのため、実際のメールは送信されません。",complete:"デモ購入完了",saveNumber:"この番号を保存してください。「注文状況」で注文番号だけを使って購入商品を確認できます。"}:language==="my"?{accessoriesTitle:"ဆိုင်ကယ်အသုံးအဆောင်ပစ္စည်းများ",accessoriesText:"ဦးထုပ်၊ အကာအကွယ်ဝတ်စုံ၊ သိုလှောင်ပစ္စည်းနဲ့ လုံခြုံရေးပစ္စည်းတွေကို ဆိုင်ကယ်နဲ့အတူ Cart ထဲထည့်နိုင်ပါတယ်။",lookupTitle:"ဝယ်ယူထားတာကို စစ်မယ်",lookupText:"Sample Website ဖြစ်တဲ့အတွက် Email မလိုပါဘူး။ ဝယ်ပြီးရတဲ့ Order Number တစ်ခုတည်းနဲ့ စစ်နိုင်ပါတယ်။",orderNumber:"Order Number",check:"Order စစ်မယ်",checking:"စစ်နေသည်…",confirmTitle:"Order အတည်ပြုမယ်",demoPayment:"PORTFOLIO · DEMO PAYMENT",locked:"Card Payment · Demo သာ",lockedText:"Payment အချက်အလက်ကို ပိတ်ထားလို့ စာရိုက်ထည့်လို့မရပါ။",noCharge:"တကယ့်ငွေမကောက်ပါ",noChargeText:"Email နဲ့ တကယ့်ငွေပေးချေမှု မလိုပါဘူး။ Confirm နှိပ်ရင် Sample Order Number ရပါမယ်။",confirm:"Demo Order အတည်ပြုမယ်",confirming:"အတည်ပြုနေသည်…",orderTip:"Order Status မှာ Order Number တစ်ခုတည်းနဲ့ ပြန်ကြည့်နိုင်ပါတယ်။",contactNote:"Portfolio Sample ဖြစ်တဲ့အတွက် တကယ့် Email သို့ မပို့ပါ။",complete:"Demo ဝယ်ယူမှု ပြီးပါပြီ",saveNumber:"ဒီနံပါတ်ကို မှတ်ထားပါ။ Order Status မှာ ဒီနံပါတ်တစ်ခုတည်းနဲ့ ဝယ်ထားတဲ့ပစ္စည်းတွေကို ပြန်ကြည့်နိုင်ပါတယ်။"}:{accessoriesTitle:"Motorcycle gear & accessories",accessoriesText:"Add helmets, protection, luggage and security products to the same cart as a motorcycle.",lookupTitle:"Check your purchase",lookupText:"This is a sample site, so no email is needed. Check an order using only the order number shown after purchase.",orderNumber:"Order number",check:"Check order",checking:"Checking…",confirmTitle:"Confirm your order",demoPayment:"PORTFOLIO · DEMO PAYMENT",locked:"Card payment · Demo only",lockedText:"Payment information is locked and cannot be typed into.",noCharge:"NO REAL CHARGE",noChargeText:"No email or real payment is required. Confirming creates a sample order number.",confirm:"Confirm demo order",confirming:"Confirming…",orderTip:"Use only the order number in Order Status to view it again.",contactNote:"This portfolio sample does not send a real email.",complete:"Demo purchase complete",saveNumber:"Save this number. Use only the order number in Order Status to view the purchased products."};
  const demoCopy=language==="ja"?{badge:"PORTFOLIO SAMPLE",text:"制作実績として作成した架空のバイクショップです。商品・在庫・注文・決済はすべてサンプルで、実際の請求はありません。",footer:"ポートフォリオ用の架空店舗です。商品・在庫・連絡先はサンプルです。"}:language==="my"?{badge:"PORTFOLIO SAMPLE",text:"ဒီ Website က Portfolio အတွက် ဖန်တီးထားတဲ့ ဆိုင်ကယ်ဆိုင် Sample ဖြစ်ပါတယ်။ ပစ္စည်း၊ လက်ကျန်၊ Order နဲ့ Payment အားလုံးက Sample ဖြစ်ပြီး တကယ့်ငွေမကောက်ပါ။",footer:"Portfolio အတွက် ဖန်တီးထားသော ဆိုင် Sample ဖြစ်ပြီး ပစ္စည်း၊ လက်ကျန်နှင့် ဆက်သွယ်ရန်အချက်အလက်များသည် Sample ဖြစ်သည်။"}:{badge:"PORTFOLIO SAMPLE",text:"A fictional motorcycle store built as a portfolio project. Products, stock, orders and payment are samples; no real charge is made.",footer:"A fictional portfolio storefront. Products, inventory and contact details are sample content."};
  const visibleBikes=useMemo(()=>bikes.filter((bike)=>{ const categoryMatch=category==="All"||(category==="Recommended"?recommendedIds.has(bike.id):bike.category===category); const conditionMatch=condition==="Any"||bike.condition===condition; const priceMatch=priceBand==="Any"||(priceBand==="Under"&&bike.price<1000000)||(priceBand==="Mid"&&bike.price>=1000000&&bike.price<=2000000)||(priceBand==="Over"&&bike.price>2000000); return categoryMatch&&conditionMatch&&priceMatch&&`${bike.name} ${bike.color}`.toLowerCase().includes(query.toLowerCase()); }),[category,condition,priceBand,query]);
  const visibleAccessories=useMemo(()=>accessoryCategory==="All"?accessories:accessories.filter((item)=>accessoryGroup(item.id)===accessoryCategory),[accessoryCategory]);
  const cartCount=cart.reduce((sum,item)=>sum+item.quantity,0); const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=window.localStorage.getItem("golden-wheel-favorites");if(saved)setFavorites(JSON.parse(saved) as string[])}catch{}finally{setFavoritesReady(true)}},0);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{if(favoritesReady)window.localStorage.setItem("golden-wheel-favorites",JSON.stringify(favorites))},[favorites,favoritesReady]);
  function addToCart(product:ShopItem){setCart((current)=>{const found=current.find((item)=>item.id===product.id);if(!found)return[...current,{...product,quantity:1}];return product.kind==="accessory"?current.map((item)=>item.id===product.id?{...item,quantity:Math.min(item.quantity+1,product.stock)}:item):current});setSelectedBike(null);setCartOpen(true)}
  function changeQuantity(id:string,delta:number){setCart((current)=>current.flatMap((item)=>item.id!==id?[item]:item.kind==="accessory"&&item.quantity+delta>0?[{...item,quantity:Math.min(item.quantity+delta,item.stock)}]:[]))}
  function toggleFavorite(id:string){setFavorites((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id])}
  function clearFilters(){setCategory("All");setCondition("Any");setPriceBand("Any");setQuery("")}
  async function submitOrder(event:FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setFormError("");const values=new FormData(event.currentTarget);try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerName:values.get("name"),phone:values.get("phone"),items:cart})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Order could not be created");setCompletedOrder(data.order.orderNumber);setCart([]);setCheckoutOpen(false);setCartOpen(false)}catch(error){setFormError(error instanceof Error?error.message:"Order could not be created")}finally{setSubmitting(false)}}
  async function trackOrder(event:FormEvent<HTMLFormElement>){event.preventDefault();setTracking(true);setTrackError("");setTrackedOrder(null);const values=new FormData(event.currentTarget);try{const response=await fetch(`/api/orders/track?orderNumber=${encodeURIComponent(String(values.get("orderNumber")))}`);const data=await response.json();if(!response.ok)throw new Error(data.error||"Order not found");setTrackedOrder(data.order)}catch(error){setTrackError(error instanceof Error?error.message:"Order not found")}finally{setTracking(false)}}
  const closeMenu=()=>setMenuOpen(false); const nav=<><a href="#models" onClick={closeMenu}>{t.bikes}</a><a href="#accessories" onClick={()=>{setAccessoryCategory("All");closeMenu()}}>Accessories</a><a href="#orders" onClick={closeMenu}>Order status</a><a href="#service" onClick={closeMenu}>{t.service}</a><a href="#contact" onClick={closeMenu}>{t.contact}</a></>;
  return <main>
    <aside className="demo-banner" aria-label={demoCopy.badge}><strong>{demoCopy.badge}</strong><span>{demoCopy.text}</span></aside>
    <header className="header"><a className="brand" href="#top"><span className="logo">GW</span><span>GOLDEN <b>WHEEL</b></span></a><nav className="desktop-nav" aria-label="Main navigation">{nav}</nav><div className="header-actions"><label className="language-picker"><span>🌐</span><select value={language} onChange={(e)=>setLanguage(e.target.value as Language)} aria-label="Language"><option value="en">EN</option><option value="ja">日本語</option><option value="my">မြန်မာ</option></select></label><button className="cart-button" onClick={()=>setCartOpen(true)}>{t.cart}<span>{cartCount}</span></button><button className="menu-button" aria-label={t.menu} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><i/><i/><i/></button></div>{menuOpen&&<div className="mobile-nav"><div>{nav}</div><button onClick={closeMenu}>{t.close} ×</button></div>}</header>
    <section className="hero" id="top"><Image src="/images/golden-wheel-hero.png" alt="Golden Wheel motorcycle showroom model" fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-ring" aria-hidden="true"/><div className="hero-rail" aria-hidden="true"><span>GOLDEN WHEEL</span><b>EST. 2026</b></div><div className="hero-copy"><div className="hero-kicker"><span>{t.collection}</span><b>01 — 16</b></div><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}<br/><em>{t.accent}</em></h1><p className="lead">{t.lead}</p><div className="hero-actions"><a className="primary" href="#models">{t.view}</a><a href="#contact" className="secondary">{t.test} →</a></div></div><div className="featured-mark"><span>FEATURED</span><strong>GW 1800</strong><small>GRAND TOUR</small></div><div className="stats"><div><strong>16</strong><span>{t.available}</span></div><div><strong>2 YEARS</strong><span>{t.warranty}</span></div><div><strong>WORKSHOP</strong><span>{t.support}</span></div></div></section>
    <section className="models" id="models"><div className="section-head"><div><p className="eyebrow">{t.stock}</p><h2>{t.choose}</h2></div><p>{t.intro}</p></div><div className="filters"><div className="tabs">{["All","Recommended","Street","Adventure","Classic","Cruiser","Bobber","Chopper","Touring","Sport"].map((item)=><button className={category===item?"active":""} key={item} onClick={()=>setCategory(item)}>{item==="All"?t.all:item==="Recommended"?`★ ${t.recommended}`:item}</button>)}</div><label className="search"><span>⌕</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search}/></label></div><div className="advanced-filters"><label>{t.condition}<select value={condition} onChange={(e)=>setCondition(e.target.value)}><option value="Any">{t.any}</option><option value="New">{t.new}</option><option value="Used">{t.used}</option></select></label><label>{t.price}<select value={priceBand} onChange={(e)=>setPriceBand(e.target.value)}><option value="Any">{t.any}</option><option value="Under">{t.under1}</option><option value="Mid">{t.oneToTwo}</option><option value="Over">{t.over2}</option></select></label><button onClick={clearFilters}>{t.clear}</button></div><p className="results-count">{t.showing} {visibleBikes.length} / {bikes.length} {t.units}</p>{visibleBikes.length===0?<div className="no-results"><p>{t.noResults}</p><button onClick={clearFilters}>{t.clear}</button></div>:<div className="bike-grid">{visibleBikes.map((bike)=><article className="bike-card" key={bike.id}>{recommendedIds.has(bike.id)&&<span className="recommend-badge">★ {t.recommended}</span>}<button className={`favorite-button ${favorites.includes(bike.id)?"saved":""}`} onClick={()=>toggleFavorite(bike.id)} aria-label={`${t.favorite}: ${bike.name}`}>{favorites.includes(bike.id)?"♥":"♡"}</button><button className="bike-photo" style={{backgroundImage:`url(${bike.image})`,backgroundPosition:bike.position}} onClick={()=>setSelectedBike(bike)} aria-label={`${t.details}: ${bike.name}`}/><div className="bike-body"><div className="bike-meta"><span>{bike.category}</span><span>{bike.engine}</span></div><h3>{bike.name}</h3><p>{bike.description}</p><div className="stock-line"><span>{bike.condition==="New"?t.new:t.used}</span><span>● {t.inStock} · {bike.stock}</span></div><div className="bike-footer"><div><small>{t.price}</small><strong>¥{bike.price.toLocaleString()}</strong></div><button onClick={()=>setSelectedBike(bike)}>{t.details}</button></div></div></article>)}</div>}</section>
    <section className="accessories" id="accessories"><div className="section-head"><div><p className="eyebrow">RIDER ESSENTIALS · {accessories.length} ITEMS</p><h2>{ui.accessoriesTitle}</h2></div><p>{ui.accessoriesText}</p></div><div className="accessory-categories" aria-label="Accessory categories">{accessoryGroups.map((group)=>{const count=group==="All"?accessories.length:accessories.filter((item)=>accessoryGroup(item.id)===group).length;return <button key={group} className={accessoryCategory===group?"active":""} onClick={()=>setAccessoryCategory(group)}><span>{group}</span><b>{count}</b></button>})}</div><p className="accessory-result">{accessoryCategory} · {visibleAccessories.length} items</p><div className="accessory-grid">{visibleAccessories.map((item)=><article className="accessory-card" key={item.id}><div className="accessory-photo" style={{backgroundImage:`url(${item.image})`,backgroundPosition:item.position}}/><div><small>{accessoryGroup(item.id)}</small><h3>{item.name}</h3><p>{item.description}</p><span>● {t.inStock} · {item.stock}</span><footer><strong>¥{item.price.toLocaleString()}</strong><button onClick={()=>addToCart(item)}>＋ {t.add}</button></footer></div></article>)}</div></section>
    <section className="service" id="service"><p className="eyebrow">{t.serviceLabel}</p><h2>{t.serviceTitle}</h2><div className="service-grid"><article><span>01</span><h3>{t.select}</h3><p>{t.selectText}</p></article><article><span>02</span><h3>{t.finance}</h3><p>{t.financeText}</p></article><article><span>03</span><h3>{t.care}</h3><p>{t.careText}</p></article></div></section>
    <section className="order-tracker" id="orders"><div><p className="eyebrow">CUSTOMER ORDER LOOKUP</p><h2>{ui.lookupTitle}</h2><p>{ui.lookupText}</p></div><form className="single-field" onSubmit={trackOrder}><label>{ui.orderNumber}<input name="orderNumber" placeholder="GW-XXXXXXXX" required/></label><button className="place-order" disabled={tracking}>{tracking?ui.checking:ui.check}</button>{trackError&&<p className="form-error">{trackError}</p>}</form>{trackedOrder&&<article className="track-result"><div><span className="status">{trackedOrder.status}</span><h3>{trackedOrder.orderNumber}</h3><small>{new Date(trackedOrder.createdAt).toLocaleString()}</small></div><ul>{trackedOrder.items.map((item)=><li key={item.name}><span>{item.name} × {item.quantity}</span><strong>¥{(item.price*item.quantity).toLocaleString()}</strong></li>)}</ul><p><span>{t.total}</span><strong>¥{trackedOrder.total.toLocaleString()}</strong></p></article>}</section>
    <section className="contact" id="contact"><div className="contact-copy"><p className="eyebrow">{t.contactLabel}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><button className="primary demo-contact" type="button" disabled>{t.message} · DEMO</button><small className="contact-demo-note">{ui.contactNote}</small></div><div className="contact-cards"><article><span>01</span><small>{t.hours}</small><strong>{t.hoursText}</strong></article><article><span>02</span><small>{t.location}</small><strong>{t.locationText}</strong></article><article><span>03</span><small>{t.call}</small><strong>{t.callText}</strong></article></div></section>
    <footer><div className="brand"><span className="logo">GW</span><span>GOLDEN <b>WHEEL</b></span></div><p>{demoCopy.footer}</p><div><span>CONTACT · SAMPLE ONLY</span><span>© 2026 Golden Wheel · Portfolio Demo</span></div></footer>
    {selectedBike&&<div className="modal-layer" role="dialog" aria-modal="true" aria-label={selectedBike.name}><button className="drawer-shade" onClick={()=>setSelectedBike(null)} aria-label={t.close}/><section className="detail-modal"><button className="modal-close" onClick={()=>setSelectedBike(null)} aria-label={t.close}>×</button><div className="detail-photo" style={{backgroundImage:`url(${selectedBike.image})`,backgroundPosition:selectedBike.position}}/><div className="detail-copy"><p className="eyebrow">{selectedBike.category} · {selectedBike.engine}</p><h2>{selectedBike.name}</h2><p>{selectedBike.description}</p><dl><div><dt>{t.year}</dt><dd>{selectedBike.year}</dd></div><div><dt>{t.color}</dt><dd>{selectedBike.color}</dd></div><div><dt>{t.condition}</dt><dd>{selectedBike.condition==="New"?t.new:t.used}</dd></div><div><dt>{t.status}</dt><dd>{t.inStock} · {selectedBike.stock}</dd></div></dl><div className="detail-price"><span>{t.price}</span><strong>¥{selectedBike.price.toLocaleString()}</strong></div><button className="place-order" onClick={()=>addToCart(selectedBike)}>{t.add}</button></div></section></div>}
    {cartOpen&&<div className="drawer-layer" role="dialog" aria-modal="true" aria-label={t.cart}><button className="drawer-shade" onClick={()=>setCartOpen(false)} aria-label={t.close}/><aside className="drawer"><div className="drawer-head"><div><p className="eyebrow">{t.selection}</p><h2>{t.cart}</h2></div><button onClick={()=>setCartOpen(false)} aria-label={t.close}>×</button></div>{cart.length===0?<div className="empty"><p>{t.empty}</p><button onClick={()=>setCartOpen(false)}>{t.explore}</button></div>:<><div className="cart-items">{cart.map((item)=><article key={item.id}><div className="cart-thumb" style={{backgroundImage:`url(${item.image})`,backgroundPosition:item.position,backgroundSize:item.kind==="accessory"?"400% 200%":"200% 200%"}}/><div><h3>{item.name}</h3><p>¥{item.price.toLocaleString()}</p><div className={`qty ${item.kind==="accessory"?"":"single"}`}><button onClick={()=>changeQuantity(item.id,-1)}>−</button><span>{item.quantity}</span><button onClick={()=>changeQuantity(item.id,1)}>＋</button></div></div></article>)}</div><div className="cart-total"><span>{t.total}</span><strong>¥{total.toLocaleString()}</strong></div><button className="checkout" onClick={()=>{setCheckoutOpen(true);setCartOpen(false)}}>{t.continue}</button></>}</aside></div>}
    {checkoutOpen&&<div className="modal-layer" role="dialog" aria-modal="true" aria-label={t.request} onKeyDown={(event)=>{if(event.key==="Escape")setCheckoutOpen(false)}}><button className="drawer-shade" onClick={()=>setCheckoutOpen(false)} aria-label={t.close}/><section className="order-modal"><div className="modal-top"><div><p className="eyebrow">{ui.demoPayment}</p><h2>{ui.confirmTitle}</h2></div><button onClick={()=>setCheckoutOpen(false)} aria-label={t.close}>×</button></div><div className="order-summary"><span>{cartCount} items</span><strong>¥{total.toLocaleString()}</strong></div><form onSubmit={submitOrder}><label>{t.name}<input name="name" required autoComplete="name"/></label><label>{t.phone}<input name="phone" type="tel" required autoComplete="tel"/></label><div className="locked-payment" aria-label="Demo payment details are locked"><span>{ui.locked}</span><strong>•••• •••• •••• ••••</strong><small>{ui.lockedText}</small></div><p className="payment-note"><strong>{ui.noCharge}</strong>{ui.noChargeText}</p>{formError&&<p className="form-error">{formError}</p>}<button className="place-order" disabled={submitting}>{submitting?ui.confirming:ui.confirm}</button><small>{ui.orderTip}</small></form></section></div>}
    {completedOrder&&<div className="modal-layer" role="dialog" aria-modal="true" aria-label={t.received}><section className="success-modal"><span className="success-logo">GW</span><p className="eyebrow">ORDER CONFIRMED</p><h2>{ui.complete}</h2><p>{ui.orderNumber}: <strong>{completedOrder}</strong></p><p>{ui.saveNumber}</p><button onClick={()=>setCompletedOrder("")}>{t.return}</button></section></div>}
  </main>
}
